env:
  browser: true
  commonjs: true
  es2020: true

extends:
  - 'plugin:react/recommended'
  - standard
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
plugins:
  - react
  - '@typescript-eslint'
rules: 
  indent: [1, 2]
  no-unused-vars: 0
  no-useless-constructor: 0
  space-before-function-paren: 0
  react/prop-types: 0
  prefer-const: 0